### PR TITLE
Fix iconset generation

### LINKED ISSUE #67: Vaadin_V/H is outdated
The vaadin icons for our company logo still shows the old version (the V has serifs), the new one is sans serif.

Old: 
image

New:
image

### PR DESCRIPTION
**Pull request by Haprog**
Now "gulp icons" generates the vaadin-icons.html in the format as we have it now (including comments) so that no manual modifications to vaadin-icons.html are needed and the file can be easily generated after SVG source files for the icons have been updated.

Also added a notice at the top of the generated file that it is generated with this task.

Generated new version of vaadin-icons.html based on current SVG sources.
Icons that were updated in vaadin-icons.html:
- vaadin-h
- vaadin-v
- workplace

Fixes #67

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/75)

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
     .pipe(concat('vaadin-icons.html'))
     .pipe(modify({
       fileModifier: function(file, contents) {
+        /* eslint-disable max-len */
         // Enclose all icons in an iron-iconset-svg
-        return `<link rel="import" href="../iron-icon/iron-icon.html">
+        return /* html */`<!-- NOTICE: Generated with 'gulp icons' -->
+<!--
+@license
+Copyright (c) 2015-2017 Vaadin Ltd.
```
Comment (web-padawan) [inline gulpfile.js]: let's update to 2015-2019

File: gulpfile.js [hunk 2]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
...
+specify the icon as \`vaadin:<icon>\`. For example, to use a cart icon, you would
+use:
+\`\`\`html
+<link rel="import" href="/components/vaadin-icons/vaadin-icons.html">
+<iron-icon icon="vaadin:cart"></iron-icon>
+\`\`\`
+
+For the complete list of available icons, see https://vaadin.com/icons
+@pseudoElement vaadin-icons
+@demo demo/
```
Comment (web-padawan) [inline gulpfile.js]: shouldn't the `demo/` be removed from here?

File: gulpfile.js [hunk 3]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
...
+Copyright (c) 2015-2017 Vaadin Ltd.
+This program is available under Apache License Version 2.0, available at https://vaadin.com/license/
+-->
+
+<link rel="import" href="../iron-icon/iron-icon.html">
 <link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html">
-<iron-iconset-svg name="vaadin-icons" size="16">
+
+<!--
+\`vaadin-icons\` is a set of 600+ icons which can be used together with Polymer's [\`iron-icon\`](https://elements.polymer-project.org/elements/iron-icon) component.
```
Comment (web-padawan) [inline gulpfile.js]: let's update the link to https://www.webcomponents.org/element/@polymer/iron-icon
the current one is a redirect and can presumably stop working any time

File: gulpfile.js [hunk 4]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
...
+
+To use the \`vaadin-icons\` iconset, import the specific \`vaadin-icons.html\`, and
+specify the icon as \`vaadin:<icon>\`. For example, to use a cart icon, you would
+use:
+\`\`\`html
+<link rel="import" href="/components/vaadin-icons/vaadin-icons.html">
+<iron-icon icon="vaadin:cart"></iron-icon>
+\`\`\`
+
+For the complete list of available icons, see https://vaadin.com/icons
```
Comment (web-padawan) [inline gulpfile.js]: Let's change the link to https://vaadin.com/components/vaadin-icons

File: gulpfile.js [hunk 5]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
...
+-->
+
+<link rel="import" href="../iron-icon/iron-icon.html">
 <link rel="import" href="../iron-iconset-svg/iron-iconset-svg.html">
-<iron-iconset-svg name="vaadin-icons" size="16">
+
+<!--
+\`vaadin-icons\` is a set of 600+ icons which can be used together with Polymer's [\`iron-icon\`](https://elements.polymer-project.org/elements/iron-icon) component.
+
+To use the \`vaadin-icons\` iconset, import the specific \`vaadin-icons.html\`, and
```
Comment (web-padawan) [inline gulpfile.js]: Same comment goes to the npm version, so I would recommend to update it, remove the and point to the "installation" docs in README: https://github.com/vaadin/vaadin-icons#installation

File: gulpfile.js [hunk 6]
```diff
@@ -21,15 +21,40 @@ gulp.task('default', function() {
...
+specify the icon as \`vaadin:<icon>\`. For example, to use a cart icon, you would
+use:
+\`\`\`html
+<link rel="import" href="/components/vaadin-icons/vaadin-icons.html">
```
Comment (web-padawan) [inline gulpfile.js]: Let's remove this import, too.

**Review by web-padawan — CHANGES_REQUESTED** [review]

File: gulpfile.js (hunk 2 above)
Comment (Haprog) [reply gulpfile.js]: You're right. Somehow I didn't notice to update this part as these were originally based on older version. Will fix.

File: gulpfile.js (hunk 3 above)
Comment (Haprog) [reply gulpfile.js]: Good idea.

File: gulpfile.js (hunk 4 above)
Comment (Haprog) [reply gulpfile.js]: Ok. I was thinking about that but thought shorter one looks better and I'm pretty sure that short redirect is also used elsewhere on vaadin.com.

Comment (Haprog) [reply gulpfile.js]: Since here it talks about "list of available icons" I would link directly to https://vaadin.com/components/vaadin-icons/html-examples which actually directly shows the list of all icons.

File: gulpfile.js (hunk 2 above)
Comment (Haprog) [reply gulpfile.js]: Fixed.

File: gulpfile.js (hunk 1 above)
Comment (Haprog) [reply gulpfile.js]: Updated.

File: gulpfile.js (hunk 3 above)
Comment (Haprog) [reply gulpfile.js]: Done.

File: gulpfile.js (hunk 4 above)
Comment (Haprog) [reply gulpfile.js]: Updated to https://vaadin.com/components/vaadin-icons/html-examples

Is that ok?

File: gulpfile.js (hunk 6 above)
Comment (Haprog) [reply gulpfile.js]: Done.

File: gulpfile.js (hunk 5 above)
Comment (Haprog) [reply gulpfile.js]: Updated the text. Is it ok now?

**Review by web-padawan — APPROVED** [review]
